name: free_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.1.0
  flutter_riverpod: ^2.4.10
  formz: ^0.7.0
  go_router: ^13.2.0
  image_picker: ^1.0.7
  json_annotation: ^4.8.1
  permission_handler: ^11.3.0
  riverpod_annotation: ^2.3.4
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
