name: free_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3

  # Others
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_image_compress: ^2.1.0
  formz: ^0.7.0
  go_router: ^13.2.0
  image_picker: ^1.0.7
  permission_handler: ^11.3.0

  # Annotations
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
